name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Update dependencies
      run: |
        go get -u ./...
        go mod tidy

    - name: Run tests
      run: go test -v -race ./...

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'chore: update Go dependencies'
        title: 'chore: update Go dependencies'
        body: |
          Automated dependency update

          This PR updates Go dependencies to their latest versions.

          Please review the changes and ensure all tests pass.
        branch: deps/auto-update
        delete-branch: true
        labels: dependencies
